version: "3.9"

services:
  nginx:
    image: nginx:1.27-alpine
    container_name: pix-nginx
    ports:
      - "80:80"
    volumes:
      - ./ops/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      pix-api:
        condition: service_healthy

  pix-api:
    build:
      context: .
      dockerfile: pix-api/Dockerfile
    container_name: pix-api
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - AWS_REGION=sa-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 60s
    depends_on:
      localstack:
        condition: service_healthy

  localstack:
    image: localstack/localstack:3.0
    container_name: localstack
    environment:
      - SERVICES=dynamodb
      - AWS_DEFAULT_REGION=sa-east-1
      - DEBUG=1
      - PERSISTENCE=1
      - LAMBDA_EXECUTOR=local
      - LOCALSTACK_HOST=localstack
    ports:
      - "4566:4566"
    volumes:
      - ./ops/localstack:/etc/localstack/init/ready.d
      - localstack_data:/var/lib/localstack
    healthcheck:
      test: ["CMD-SHELL", "awslocal dynamodb list-tables >/dev/null 2>&1"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 15s



  prometheus:
    image: prom/prometheus:v2.54.1
    container_name: prometheus
    volumes:
      - ./ops/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:11.1.4
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus

  portainer:
    image: portainer/portainer-ce:2.21.1
    container_name: portainer
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

volumes:
  portainer_data:
  localstack_data: