services:
  nginx:
    image: nginx:1.27-alpine
    container_name: pix-nginx
    ports:
      - "80:80"
    volumes:
      - ./ops/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      pix-api:
        condition: service_healthy

  pix-api:
    image: docker.io/scaputo88/pix-api:latest
    container_name: pix-api
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8080/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      - localstack

  localstack:
    image: localstack/localstack:3.7
    container_name: localstack
    environment:
      - SERVICES=sqs,sns,s3,dynamodb
      - DEBUG=1
    ports:
      - "4566:4566"

  prometheus:
    image: prom/prometheus:v2.54.1
    container_name: prometheus
    volumes:
      - ./ops/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:11.1.4
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus

  portainer:
    image: portainer/portainer-ce:2.21.1
    container_name: portainer
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: pixdb
      POSTGRES_USER: pixuser
      POSTGRES_PASSWORD: pixpass
    ports:
      - "5432:5432"

volumes:
  portainer_data: