aws:
  region: sa-east-1
  dynamodb:
    endpoint: http://localstack:4566

spring:
  main:
    allow-bean-definition-overriding: true
  cloud:
    aws:
      region:
        static: sa-east-1
      credentials:
        access-key: test
        secret-key: test
      sqs:
        enabled: false
      sns:
        enabled: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always

logging:
  level:
    root: INFO
    software.amazon.awssdk: WARN
    io.awspring.cloud: WARN